### ISSUE TITLE
Moving conditionals around

### ISSUE THREAD

**Issue by moll** [AndrewRadev/sideways.vim#13]
Lo again,

I've quite often found myself wanting to move conditionals around. They're parse very similarly to function arguments, but are delimited by `&&` and `||` rather than commas. You reckon it's possible to get Sideways.vim working with those too?

Merci in advance!

**Comment by AndrewRadev** [comment]
Sorry it took a while to respond to this.

I actually did try to implement those. In fact, the functionality for it is still there, even if it's incomplete. I'm not sure what language you need this for, but I'll talk about ruby, since this is most familiar to me. Try this:

``` ruby
if foo && bar
  bla
end
```

If you put the cursor on `foo` and move right, it works just fine. Unfortunately, with the cursor on `bar`, it doesn't work, because it detects `foo` as a function call, and `&& bar` as its single argument.

With nested structures, the closest one takes precedence (otherwise it'd be impossible to work with any kind of nested function call), which is why it doesn't work. Of course, `&& bar` is not a valid function argument, but parsing ASTs is far beyond the means of the plugin.

If I remove the method detection for ruby, it works, but even then, it doesn't work within nested `(foo && bar)`-style structures, since they're just wrapped in brackets, no `if`-clause to detect anything inside. This might be fixable, but either way, removing the method detection would make the plugin a lot less useful.

I can't think of any sensible way to get this done, to be honest.

**Comment by hgiesel** [comment]
I don't this should be implemented `foo && bar` and `bar && foo` are functionally equivalent, so there is no point.

**Comment by moll** [comment]
Depends on the language. In languages with short circuiting, they're not equivalent. Even if pure, not necessarily equivalent in the amount of work done.

As for this feature in Sideways.vim, if @AndrewRadev says it's too cumbersome to add, we can close this proposal and consider it something nice to have for someone else to implement. Perhaps by that time we'll all be on symbolic editors anyways. ^_^

**Comment by AndrewRadev** [comment]
> Perhaps by that time we'll all be on symbolic editors anyways. 

Given the speed at which I manage to work on my github issues, it might just turn out like that, sadly :).

**Comment by moll** [comment]
No probs. It's OSS, after all. We all work on it whenever we feel like it. It's not like we get paid for this. :D

**Comment by moll** [comment]
I'll close this issue to not leave things lingering for @AndrewRadev.

**Comment by andreiglingeanu** [comment]
> Perhaps by that time we'll all be on symbolic editors anyways.

I'm sorry, what's the symbolic editors thing all about?
